/**
 * Blur data URLs for image placeholders
 * These are tiny base64-encoded versions of the images for instant loading
 *
 * To generate a blur placeholder:
 * 1. Use a 10x10px version of the image
 * 2. Convert to base64: data:image/jpeg;base64,...
 */

// Simple gradient placeholder for portraits (dark theme compatible)
export const PORTRAIT_BLUR =
  'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMCwsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABwYI/8QAIhAAAQMEAgMBAAAAAAAAAAAAAQIDBAAFBhESIQcTMUH/xAAVAQEBAAAAAAAAAAAAAAAAAAADBP/EABsRAAICAwEAAAAAAAAAAAAAAAECABEDEiEx/9oADAMBEQCEAPwAnOMTL1aciixMhuEyahfXEpJPsJCkNpG+Xf7UlxrN8xsclt5m6zUtqPdLmxr/AKlKU4Wll4A+VJ7Jf//Z'

// Abstract background placeholder
export const ABSTRACT_BG_BLUR =
  'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMCwsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABgcI/8QAIRAAAQQBBAMBAAAAAAAAAAAAAQIDBAUGABESIQcTMUH/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//EABkRAAIDAQAAAAAAAAAAAAAAAAECAAMhMf/aAAwDAQACEQMRAD8Ao2A5HkOOZWLxDOrkxKGLl95UZ11KgpKFAJPLftBNJjOdXV+u5yn1SJTqwXFKUdDegBNGgKUZwB0J/9k='

// Logo placeholder (simple dark)
export const LOGO_BLUR =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAAFklEQVQoU2NkYGD4z0AEYBxVSF+FABJAAgGMwnmDAAAAAElFTkSuQmCC'

// Testimonial placeholder (person silhouette)
export const TESTIMONIAL_BLUR =
  'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMCwsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABwUG/8QAIhAAAQMDBAMBAAAAAAAAAAAAAQIDBAUGEQAHEiETMUFR/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAP/xAAZEQACAwEAAAAAAAAAAAAAAAABAgADESH/2gAMAwEAAhEDEEEAPwCJZG4d5R7npbU29KgWqE/HnPsJadPrKQccTn1kdfNVJV5XDCqM6NHuSsMsNSHG2m0y1gJQFEJAGewBjWpWoA65P//Z'

// Business/meeting image placeholder
export const BUSINESS_BLUR =
  'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMCwsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAAKAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABgcI/8QAIhAAAQMDBAMBAAAAAAAAAAAAAQIDBAUGEQAHEiETQVFh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAX/xAAaEQACAwEBAAAAAAAAAAAAAAABAgADESEx/9oADAMBEQCEAPwCr2zfdxWnX6dHod0VGnxnZTLL7MWQptDrfMBaFA9EYOCNCLmuW5K1cVQmVK5atMkPSFuOuvzFrU4oqJKiT2ST3o0rNgALdU//2Q=='

/**
 * Get responsive image sizes for common layouts
 */
export const IMAGE_SIZES = {
  // Hero portrait - full width on mobile, 540px on desktop
  heroPortrait: '(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 540px',

  // Full width background
  fullWidth: '100vw',

  // Logo in header
  headerLogo: '40px',

  // Testimonial avatar
  testimonialAvatar: '56px',

  // Small profile image
  profileSmall: '64px',

  // Card image
  cardImage: '(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw',
} as const
